added first Individual Task
sergeychur/TP_CPP_HOMEWORK pull request #1
Opened 2018-10-06 15:34 UTC by sergeychur

2018-10-07 15:15 UTC, leshiy1295 requested changes

2018-10-07 15:15 UTC, leshiy1295 commented on a_6.c
> +	fputs("[error]\n", stderr);
зачем ещё один \n, если используется puts?

2018-10-07 15:15 UTC, leshiy1295 commented on a_6.c
> +	char** line;
почему line - двойной указатель? из названия это не очевидно

2018-10-07 15:15 UTC, leshiy1295 commented on a_6.c
> +	// place the strig nto the end aof thre array
с комментарием что-то пошло не так
и лучше комментарии по поводу поведения оставлять до заголовка функции

2018-10-07 15:15 UTC, leshiy1295 commented on a_6.c
> +		dst->line = (char**)realloc(dst->line, sizeof(char*) * new_capacity);
realloc не освобождает память при ошибке, и она доступна по старому указателю
сейчас же Вы его перезатираете, что приводит к утечке

2018-10-07 15:15 UTC, leshiy1295 commented on a_6.c
> +				continue;
крайне не рекомендуется использовать continue

2018-10-07 15:15 UTC, leshiy1295 commented on a_6.c
> +		if(push_back(&str_arr, line) != 0) {
можно оставить и без != 0 - в C 0 - это false
но если в таком формате, то лучше вынести 0 в именованную константу

2018-10-07 15:15 UTC, leshiy1295 commented on a_6.c
> +		free_arr(&str_arr);
подумайте, как можно побороться с дублированием кода free

2018-10-07 15:15 UTC, leshiy1295 commented on a_6.c
> +int main(void) {
функция main очень большая - нужно декомпозировать в виде:
- ввод и инициализация ресурсов
- обработка
- вывод и освобождение ресурсов
сам файл лучше организовать следующим образом:
- описания функций (интерфейс)
- определение main
- определения всех остальных функций

2018-10-07 15:15 UTC, leshiy1295 commented on a_6.c
> +#define ERR_EMPTY_PTR -1
много разных ошибок, но они нигде не используются в итоге => их можно либо убрать, либо выводить в stderr, например

2018-10-07 18:37 UTC, sergeychur commented on a_6.c
> +	fputs("[error]\n", stderr);
убрал

2018-10-07 18:38 UTC, sergeychur commented on a_6.c
> +	char** line;
переименовал в line_array

2018-10-07 18:41 UTC, sergeychur commented on a_6.c
> +	// place the strig nto the end aof thre array
перенес

2018-10-07 19:19 UTC, sergeychur commented on a_6.c
> +		dst->line = (char**)realloc(dst->line, sizeof(char*) * new_capacity);
поменял на выделение с помощью malloc по новому указателю и перекидывание старого на него

2018-10-07 19:23 UTC, sergeychur commented on a_6.c
> +				continue;
убрал

2018-10-07 19:24 UTC, sergeychur commented on a_6.c
> +		if(push_back(&str_arr, line) != 0) {
поменял на SUCCESS. Иначе код становится не очень понятным.

2018-10-07 19:25 UTC, sergeychur commented on a_6.c
> +		if(push_back(&str_arr, line) != 0) {
if(push_back()) {} читается как : если push_back прошел, делай то...

2018-10-07 20:04 UTC, sergeychur commented on a_6.c
> +		free_arr(&str_arr);
Попытался исправить. Сделал переменную, в которую падают ошибки. Она равна SUCCESS, только если все хорошо. Таким образом, программа не останавливает работу сразу после ошибки, она доходит до конца, где освобождаются ресурсы. Другие функции же не вызываются т.к. при каждом вызове проверяется переменная ошибки.

2018-10-07 21:08 UTC, sergeychur commented on a_6.c
> +#define ERR_EMPTY_PTR -1
Убрал все кроме двух. Остальные даже нигде не использовались) Оставил ERR_EMPTY_PTR и ERR_ALLOC, т.к. проще читать код. В stderr нельзя выводить по условию, а делать return ERROR не хочется(не понятно, что происходит).

2018-10-07 21:09 UTC, sergeychur commented on a_6.c
> +int main(void) {
Вынес ввод в исходный массив в отдельную функцию.

2018-10-07 21:09 UTC, sergeychur commented on a_6.c
> +int main(void) {
Теперь он (main) 10 строк

2018-10-07 21:37 UTC, leshiy1295 commented
Когда поправите все замечания - нужно прогнать повторно программу в АСТС, оставить комментарий здесь с готовностью к повторному ревью с указанием нового runId

2018-10-07 21:42 UTC, sergeychur commented
Новый Run ID - 1450

2018-10-07 21:43 UTC, sergeychur commented
Все поправил, жду ревью

2018-10-07 21:46 UTC, sergeychur commented
> Когда поправите все замечания - нужно прогнать повторно программу в АСТС, оставить комментарий здесь с готовностью к повторному ревью с указанием нового runId

Прошу прощения, просто по мере исправления для себя писал, что сделал. Думал, что Вам приходит уведомление только о том когда я уже заливаю изменения.

2018-10-08 12:44 UTC, leshiy1295 requested changes

2018-10-08 12:44 UTC, leshiy1295 commented on a_6.c
> +int copy_pointers(char**, char**, const size_t);
непонятное название функции, и из каких указателей в какие будет осуществляться копирование

2018-10-08 12:44 UTC, leshiy1295 commented on a_6.c
> +int copy_pointers(char** dst, char** src, const size_t src_size) {
если src не изменяется, то почему бы не пометить его как const?

2018-10-08 12:44 UTC, leshiy1295 commented on a_6.c
> +// place the strig nto the end aof thre array
с комментарием всё ещё что-то не так

2018-10-08 12:44 UTC, leshiy1295 commented on a_6.c
> +			return ERR_EMPTY_PTR;
делать return внутри for недопустимо из-за повышения сложности анализа поведения программы

2018-10-08 12:44 UTC, leshiy1295 commented on a_6.c
> +	if(!(src_arr.line_array)) {
что будет, если в dst_arr передадут NULL?

2018-10-08 12:44 UTC, leshiy1295 commented on a_6.c
> +	err_state += fill_src_array(&str_arr, &str_num);
обычно никто напрямую не обрабатывает значения ошибок и тем более не суммирует их. 
достаточно проверять их на [не]равенство известным именованным константам

2018-10-08 12:44 UTC, leshiy1295 commented on a_6.c
> +	free_arr(&str_arr);
зачем нужно передавать через &?

2018-10-08 17:13 UTC, sergeychur commented
https://github.com/sergeychur/TP_CPP_HOMEWORK/pull/1#discussion_r223346782 : переименовал в make_copy_of_pointers_array и сделал тот указатель на массив указателей, из которого копируется, константным. 
https://github.com/sergeychur/TP_CPP_HOMEWORK/pull/1#discussion_r223348013 : Вы попросили меня избежать дублирования кода освобождения памяти. Я сделал освобождение памяти в одном месте. Но в то же время надо было обработать ошибки и дальнейшие функции не исполнять. Поэтому попытался реализовать некоторый аналог errno, в который записывались ошибки. Убрал суммирование. Как избежать дублирование по другому не приходит в голову.
https://github.com/sergeychur/TP_CPP_HOMEWORK/pull/1#discussion_r223349356 : Если я не ошибаюсь, то при передачи переменной в функцию по значению происходит копирование её на фрейм вызываемой функции. Чтобы это избежать, я передаю переменную по адресу.









К ревью готов. Новый RunID - 1576

2018-10-15 09:57 UTC, leshiy1295 commented on a_6.c
> +	free_arr(&str_arr);
в таком случае будет передан на фрейм адрес :)
int - 4 байта, а адрес может быть 8 на 64-битной системе

2018-10-15 09:57 UTC, leshiy1295 commented on a_6.c
> +int error_end(void) {
лучше передавать FILE *stream, чем хардкодить stderr

2018-10-15 09:57 UTC, leshiy1295 commented on a_6.c
> +	if(!src && !dst) {
а если только один из них == NULL?

2018-10-15 09:57 UTC, leshiy1295 commented on a_6.c
> +			make_copy_of_pointers_array(tmp, dst->line_array, dst->size);
семантически неясно, что куда копируется
было бы лучше, например, возвращать копию в качестве результата

2018-10-15 09:57 UTC, leshiy1295 commented on a_6.c
> +	if(!(src_arr.line_array) && !dst_arr) {
аналогичный вопрос про равенство только одно из указателей NULL

2018-10-15 09:57 UTC, leshiy1295 commented on a_6.c
> +				return NULL;
такие неструктурные выходы из циклов недопустимы

2018-10-15 09:57 UTC, leshiy1295 commented on a_6.c
> +		string = (char*)malloc(2 * sizeof(char));
что если malloc упал?

2018-10-15 09:57 UTC, leshiy1295 commented on a_6.c
> +		err_state = (err_state == SUCCESS) ? push_back(str_arr, line) : 0;
было бы понятнее проверить if (==SUCCESS) {} else {}

2018-10-19 22:36 UTC, merged